# Generated by Django 5.2.5 on 2025-09-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=350)),
                ('image', models.ImageField(upload_to=True)),
                ('country', models.CharField(choices=[('Uzbekiston', 'Uzbekiston'), ('Angliya', 'Angliya'), ('Amerika', 'Amerika')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=450)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
        ),
    ]
